### ISSUE TITLE
Explain overrides

### ISSUE THREAD

**Issue by proofconstruction** [NixOS/nix.dev#678] opened 2023-08-17 18:00 UTC
There are many cases where you'd want to extend or replace part of a derivation (this came up in today's meeting discussion in the context of `mkShell`); for this you'd use an [override](https://nixos.org/manual/nixpkgs/stable/#chap-overrides), but we don't currently have a tutorial for doing so.

**Comment by akiross** [comment] 2023-09-06 19:59
Hi! Today was looking for resources about overrides and saw your issue, in which I'm quite interested.

Few hours later, I stumbled on this article which I think is clear and complete: I'd like to share it here because I think it would be great reference material for the tutorial or even provide inspiration. It is more use-case oriented than an explanation about overrides, but it might be relevant for this issue nevertheless.

https://bobvanderlinden.me/customizing-packages-in-nix/

**Comment by TLATER** [comment] 2023-09-07 14:53
Looking at [the vision page](https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md#declarative-environments), I think this would fit immediately after the shell environments tutorial, and build upon modifying packages used in a shell?

I can see that working with `.override`, I guess the overlay tutorial (#116) will refer back to this to make the differences between overlays and overrides clear?

**Comment by fricklerhandwerk** [comment] 2023-09-08 15:45
I agree, this is where it should go. See https://github.com/NixOS/nix.dev/pull/701 for the latest ideas of what it should look like.

**Comment by fricklerhandwerk** [comment] 2024-02-07 03:33
Duplicate of #731

**Closed by fricklerhandwerk** 2024-02-07 03:33 UTC
Labels: site
