### ISSUE TITLE
Issue on learn page, the nix installation link shows "Page not found"

### ISSUE THREAD

**Issue by pk0dev** [NixOS/nix.dev#1008] opened 2024-06-28 16:46 UTC
On the [Learn page](https://nixos.org/learn/) under Search Nix packages and NixOS options there is the Installation link under Nix Manual and this link is broken.

https://nix.dev/manual/nix/2.23/stable/installation/installing-binary

Page not found
Unfortunately we couldn't find the content you were looking for.

**Comment by fricklerhandwerk** [comment] 2024-06-28 19:52
Duplicate of https://github.com/NixOS/nix.dev/issues/996, will be fixed by https://github.com/NixOS/nixos-homepage/pull/1486

**Closed by fricklerhandwerk** 2024-06-28 19:52 UTC
